version: '2'
services:
  cassandra:
    image: cassandra
    ports:
    - '9042:9042'
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"


  mysql:
    image: mysql:5.5
#    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3335:3306'

  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node

  msrabbitmq:
    image: rabbitmq:3-management
    container_name: hk-msrabbitmq
#    networks:
#      - company
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin